config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: "registrations"}
  resources :tweeets
  resources :likes, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
    get '/sign-in' => "devise/sessions#new", :as => :login
  end
  

  # Defines the root path route ("/")
  root "tweeets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweeet
  validates :user_id, uniqueness: {scope: :tweeet_id}
end

app/models/tweeet.rb
class Tweeet < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweeets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        @like = current_user.likes.new(like_params)

        if !@like.save
            flash[:notice] = @like.errors.full_messages.to_sentence
        end
        
        redirect_to root_path

    end

    private

    def like_params
        params.require(:like).permit(:tweeet_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
    private

    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :avatar)
    end

    def account_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password, :avatar)
    end

end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /tweeets or /tweeets.json
  def index
    @tweeets = Tweeet.all.order("created_at DESC")
    @tweeet = Tweeet.new
  end

  # GET /tweeets/1 or /tweeets/1.json
  def show
  end

  # GET /tweeets/new
  def new 
    @tweeets = current_user.tweeets.all.order("created_at DESC")
    @tweeet = current_user.tweeets.build
    
    render :index
  end

  # GET /tweeets/1/edit
  def edit
  end

  # POST /tweeets or /tweeets.json
  def create
    @tweeet = current_user.tweeets.build(tweeet_params)
    @tweeets = current_user.tweeets.all.order("created_at DESC")

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to tweeet_url(@tweeets), notice: "Tweeet was successfully created." }
        format.json { render :index, status: :created, location: @tweeets }
      else
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }        
      end
    end
  end

  # PATCH/PUT /tweeets/1 or /tweeets/1.json
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to tweeet_url(@tweeet), notice: "Tweeet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeets/1 or /tweeets/1.json
  def destroy
    @tweeet.destroy

    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: "Tweeet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeet
      @tweeet = Tweeet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweeet_params
      params.require(:tweeet).permit(:tweeet, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twittter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification">
        <p class="notice" style="color: green"><%= notice %></p>
      </div>
    <% end %>

     <% if flash[:alert] %>
      <div class="notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <div>
         

         <%= yield %> 

    </div>    
    
   

     
  </body>
</html>

app/views/tweeets/_form.html.erb
<%= form_with(model: tweeet, class: "input") do |form| %>
  <% if tweeet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweeet.errors.count, "error") %> prohibited this tweeet from being saved:</h2>

      <ul>
        <% tweeet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input">    
    
    <% if current_user.avatar.attached? %>
        <%= image_tag current_user.avatar, class: "profile-pic input-pic" %>        
    <% else %>
        <%= image_tag "EWAJB4WUcAAje8s.png", class: "profile-pic input-pic" %>        
    <% end %>

    <%= form.text_area :tweeet, placeholder: "What's happening?" %>
  </div>

  <div>
    <%= form.submit 'New Tweeet', :class => "new-tweet-button" %>
  </div>
<% end %>

app/views/tweeets/_tweeet.html.erb
  <div class="post">
      
      <div class="post-top">
          <% if tweeet.user.avatar.attached? %>
              <%= image_tag tweeet.user.avatar, class: "profile-pic" %>                                    
              <h2 class="username"><%= tweeet.user.name %></h2>
              <span class="post_id">@<%= tweeet.user.username %></span><br>
          <% else %>
              <%= image_tag "EWAJB4WUcAAje8s.png", class: "profile-pic" %>                                    
              <h2 class="username"><%= tweeet.user.name %></h2>
              <span class="post_id">@<%= tweeet.user.username %></span><br>
          <% end %>
      </div>  
      

      <div class="post-mid">
          <p class="comment"><%= tweeet.tweeet %></p>  
      </div>

      
        <div class="post-bot">
          
            <div class="comm-icon-link">

              <%= form_with(url: likes_path, method: "post", class: "comm-icon") do%>
                <input type="hidden" name="like[tweeet_id]" value="<%= tweeet.id%>" autocomplete="off">
                <%= image_submit_tag("favorite_border_black_24dp.svg")%>
              <% end%>

            </div>            
                    
            <span class="comm-count"><%= tweeet.likes.count%></span>
          
            <% if current_user.name == tweeet.user.name %>                 
              <%= link_to tweeet, class: "view-icon-link" do%>
                  <%= image_tag "visibility_black_24dp.svg", class: "view-icon" %>  
              <% end %>  
            <% else %>  
                <%= link_to root_path, class: "view-icon-link" do%>
                  <%= image_tag "visibility_black_24dp.svg", class: "view-icon" %>  
                <% end %>              
            <% end %>   


        </div>
      
      


  </div>

  

app/views/tweeets/_tweeet_show.html.erb
<div class="post2">
    
    <div class="post-top">
        <% if tweeet.user.avatar.attached?%>
            <%= image_tag tweeet.user.avatar, class: "profile-pic2" %> 
        <% else %>
            <%= image_tag "EWAJB4WUcAAje8s.png", class: "profile-pic2" %> 
        <% end %>
                                              
        <h2 class="username2"><%= tweeet.user.name %></h2>
        <span class="post_id2">@<%= tweeet.user.username %></span><br>
    </div>  

    <div class="post-mid2">
        <p class="comment2"><%= tweeet.tweeet %></p>  
    </div>

    
      <div class="post-bot2">   

          <div class="comm-icon-link2">

            <%= form_with(url: likes_path, method: "post", class: "comm-icon2") do%>
              <input type="hidden" name="like[tweeet_id]" value="<%= tweeet.id%>" autocomplete="off">
              <%= image_submit_tag("favorite_border_black_24dp.svg")%>
            <% end%>

          </div>  
                  
          <span class="comm-count2"><%= tweeet.likes.count%></span>
        
              <%= link_to tweeet, class: "view-icon-link2"  do%>
                <%= image_tag "visibility_black_24dp.svg", class: "view-icon" %>  
              <% end %>    

      </div>
    


</div>

app/views/tweeets/edit.html.erb
<h1 class="text">Editing tweeet</h1>

<%= form_with(model: @tweeet, class: "input") do |form| %>
  <% if @tweeet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@tweeet.errors.count, "error") %> prohibited this tweeet from being saved:</h2>

      <ul>
        <% @tweeet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input">    
    <%= image_tag "1607363622_58434.jpeg", class: "profile-pic input-pic" %>
    <%= form.text_area :tweeet, placeholder: "What's happening?" %>
  </div>

  <div>
    <%= form.submit 'New Tweeet', :class => "new-tweet-button2" %>
  </div>
<% end %>

app/views/tweeets/index.html.erb
<div class="app-area">
         
  <div class="side-left">
      <a href="https://twitter.com/">
      <%= image_tag "logo-3491390_1920.svg", class:"logo" %></a>            
      
      <% if user_signed_in? %>
          <div class="menu-left">

              <div class="links-menu">                    
                  <%= link_to root_path do%>
                    <%= image_tag "home.png", class: "icon-menu" %>
                    <span class="tabs">Home</span>
                  <% end %>
              </div>

              <div class="links-menu">
                  <%= link_to edit_user_registration_path do%>
                    <%= image_tag "account.png", class: "icon-menu" %>                        
                    <span class="tabs">Profile</span>
                  <% end %>
              </div>                
              
          </div>
      <% else %>

          <div class="button_cont">
              <%= button_to "Sign In", new_user_session_path, method: :get, class: "btn"%>          
              <%= button_to "Sign Up", new_user_registration_path, method: :get, class: "btn" %>
          </div>

      <% end %>

  </div>

  <div class="my-post">
  
  </div>
  
  <div class="header">
      <div class="header-contents">
          <span>Home</span>

        <% if user_signed_in? %>
          <div class="x">
              <%= button_to "Logout", destroy_user_session_path, method: :get, class: "btn", style: "width: 97px;"%>
          </div>

        <% end %>

      </div>

  </div>       
  
  
  <div class="trends"></div>   

  <div class="posts">
      <% @tweeets.each do |tweeet| %>
        <%= render tweeet %>    
      <% end %>
  </div>
  <% if user_signed_in? %>
      <%= render "form", tweeet: @tweeet %> 
  <% end %>
        
</div>   

app/views/tweeets/show.html.erb
<div class="login-area2">
    
    <div class="posts2">

      <%= render "tweeet_show", tweeet: @tweeet %>

<div class="post-bot2">
      <%= link_to edit_tweeet_path(@tweeet), class: "edit-icon-link" do %>
        <%= image_tag "edit_black_24dp.svg", class: "edit-icon" %>
      <% end %>  

      <%= form_with(url: @tweeet, method: "post", class: "del-button") do%>
        <input type="hidden" name="_method" value="delete" autocomplete="off">
        <%= image_submit_tag("clear_black_24dp.svg", data: {confirm: "Are you sure?"})%>
      <% end%>
</div> 
      
    </div> 

</div>